app:
  name: My app
  description: Welcome to ${app.name}

my:
  greeting: Hello World from config-client.yml test test test test
  list:
    values:
      One, Two, Three
      
server:
  port: 9085
      

